# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ridemapper < Formula
  desc "Self-hosted web service for tracking motorcycle and bicycle rides"
  homepage "https://github.com/andrewslotin/ridemapper"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.slotin.me/ridemapper/v1.0.2/ridemapper_1.0.2_darwin_x86_64.tar.gz"
      sha256 "a65eb9ff172f48aedc0fd943f199823a0220c4d817af76105dfa848db960c9e0"

      define_method(:install) do
        bin.install "ridemapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.slotin.me/ridemapper/v1.0.2/ridemapper_1.0.2_darwin_arm64.tar.gz"
      sha256 "3f3aa7447fc2e0aaad8593927dc8b25794b23550fd2356fde9723be2a44fe901"

      define_method(:install) do
        bin.install "ridemapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.slotin.me/ridemapper/v1.0.2/ridemapper_1.0.2_linux_x86_64.tar.gz"
      sha256 "70901a3819057900d606ee8cbdfabad01d504d7cb2d7147211627e290a88e61e"
      define_method(:install) do
        bin.install "ridemapper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.slotin.me/ridemapper/v1.0.2/ridemapper_1.0.2_linux_arm64.tar.gz"
      sha256 "f96244862dd250201d39465ed57b4480939ee69164c50b1d6f1393562b7f7bc6"
      define_method(:install) do
        bin.install "ridemapper"
      end
    end
  end
end
