# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ridemapper < Formula
  desc "Self-hosted web service for tracking motorcycle and bicycle rides"
  homepage "https://github.com/andrewslotin/ridemapper"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.slotin.me/ridemapper/v1.1.0/ridemapper_1.1.0_darwin_x86_64.tar.gz"
      sha256 "6ddc147b7e66698f1f46b9c78579e17a79ee8067458f27a4f40aaa9357baf422"

      define_method(:install) do
        bin.install "ridemapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.slotin.me/ridemapper/v1.1.0/ridemapper_1.1.0_darwin_arm64.tar.gz"
      sha256 "150d7aed8b9684aa71b79f869232b26a55529dc4e6505fe81eca6bdaffcc9b5d"

      define_method(:install) do
        bin.install "ridemapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.slotin.me/ridemapper/v1.1.0/ridemapper_1.1.0_linux_x86_64.tar.gz"
      sha256 "17593356d50acbddc95006ea6ade2d26d20c21f67ae52a899245eb215300b762"
      define_method(:install) do
        bin.install "ridemapper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.slotin.me/ridemapper/v1.1.0/ridemapper_1.1.0_linux_arm64.tar.gz"
      sha256 "3599435018e481b77f0f3f58ef17910bdccb95b743fd7acc279fa64925f4143c"
      define_method(:install) do
        bin.install "ridemapper"
      end
    end
  end
end
