# This file was generated by GoReleaser. DO NOT EDIT.
cask "ridemapper" do
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://dl.slotin.me/ridemapper/v#{version}/ridemapper_#{version}_darwin_x86_64.tar.gz"
      sha256 "37f18aab339b75126932cbd2e6cd6ae9516340b2bd5b0819edb023a2b82906ee"
    end
    on_arm do
      url "https://dl.slotin.me/ridemapper/v#{version}/ridemapper_#{version}_darwin_arm64.tar.gz"
      sha256 "ee0743288ec126ac0a819dc0bc5d8cce13d48b9589e759783e5e1b636381a1bf"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.slotin.me/ridemapper/v#{version}/ridemapper_#{version}_linux_x86_64.tar.gz"
      sha256 "4e1bb8ad05643e9c72d66a82da9fa28239d225c85f901b378ae07a3fd883c93f"
    end
    on_arm do
      url "https://dl.slotin.me/ridemapper/v#{version}/ridemapper_#{version}_linux_arm64.tar.gz"
      sha256 "9f7bb151d5b9acc55577ba5595e145cee104036b260f93e5a6dfe3071713e2c6"
    end
  end

  name "ridemapper"
  desc "Self-hosted web service for tracking motorcycle and bicycle rides"
  homepage "https://github.com/andrewslotin/ridemapper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ridemapper"

  # No zap stanza required

end
