# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ridemapper < Formula
  desc "Self-hosted web service for tracking motorcycle and bicycle rides"
  homepage "https://github.com/andrewslotin/ridemapper"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.slotin.me/ridemapper/v2.1.0/ridemapper_2.1.0_darwin_x86_64.tar.gz"
      sha256 "e924f88ffe23cab2a9fc908fbdd11059bbc7e7b39af6c0aaaf7873cc12f0025c"

      define_method(:install) do
        bin.install "ridemapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.slotin.me/ridemapper/v2.1.0/ridemapper_2.1.0_darwin_arm64.tar.gz"
      sha256 "d239e2fdbb5d3f3dc15a043ae17ab7b46dc94c13476f59fa110fad24b556f875"

      define_method(:install) do
        bin.install "ridemapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.slotin.me/ridemapper/v2.1.0/ridemapper_2.1.0_linux_x86_64.tar.gz"
      sha256 "3e8887961269e7f44fcf25b1a90cb6e50d4ab6c1abc90a06a9f8c9fa5e35f254"
      define_method(:install) do
        bin.install "ridemapper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.slotin.me/ridemapper/v2.1.0/ridemapper_2.1.0_linux_arm64.tar.gz"
      sha256 "591c97f135fdb9514c7d89067faafac731ed6c98ce8341cc2924241f4de5593f"
      define_method(:install) do
        bin.install "ridemapper"
      end
    end
  end
end
